### ISSUE TITLE
@where cannot use defined symbol variable

### ISSUE THREAD

**Issue by mes9** [JuliaStats/DataFramesMeta.jl#23]
No issue when 
filtered_data=@where(data, :x .== 2)

but if we define 
indicator=:x
filtered_data=@where(data, indicator .== 2)

it returns an error. This makes it difficult to go though a loop using different "indicators"

**Comment by arnaudmgh** [comment]
I also almost filled an issue about that. Use ^(indicator). It's a bit
unnatural but it's how it is right now. There is a closed issue about
changing the notation.

**Comment by mes9** [comment]
Can you write out how to express it? I can't seem to get it to work

**Comment by arnaudmgh** [comment]
Sorry I misunderstood your original question. I don't know how to do that.

**Comment by johnmyleswhite** [comment]
This is the kind of thing you can't do with macros. You should work with the macro expanded representation of `@where`.

**Comment by matthieugomez** [comment]
It seems like a big issue for the macro approach.

for any function that does NSE, `dplyr` has a function that takes an expression as an argument:
```R
library("dplyr")
df = data_frame(x = c(1, 2), y = c(2, 3))
filter(df, x >= 2)
indicator = quote(x)
filter_(df, interp(~y >= 2, y = indicator))
```

Maybe, similarly for any macro in this package, there could be a function that takes a quoted expression as an argument:
```julia
using DataFrames, DataFramesMeta
df = DataFrame(x = 1:2, y = [2, 3])
@where(df, :x .>= 2)
indicator = :x
where(df, :($x >= 2)
```
It's made harder by the fact one has to construct `:(:x >=2)` rather than `:(x >= 2)` and I'm not sure how to do that.

**Comment by matthieugomez** [comment]
Actually `indicator = :(:x)` works, so one could do

```julia
using DataFrames, DataFramesMeta
df = DataFrame(x = 1:2, y = 2:3)
@where(df, :x .>= 2)
indicator = :x
where(df, :($indicator .>= 2))
```
I think it could be a pretty good thing, no?

@mes9 For now, you can see in the code that `@where` is defined by `where_expr`. So the way to do it is
```julia
using DataFrames, DataFramesMeta
df = DataFrame(x = 1:2, y = 2:3)
indicator = :(:x)
eval(DataFramesMeta.where_helper(:df, :($indicator .>= 2)))
```

**Comment by mes9** [comment]
Thank you, that clarifies a lot, but I still cannot figure out how to have it go through a loop. for example, 
```julia
using DataFrames, DataFramesMeta
df = DataFrame(x = 1:2, y = 2:3)
for i=1:2
  indicator = names(df)[i]
  eval(DataFramesMeta.where_helper(:df, :($indicator .>= 2)))
end
```
returns an error

**Comment by matthieugomez** [comment]
indicator should be `:(:x)`, not `:x`.
```julia
using DataFrames, DataFramesMeta
df = DataFrame(x = 1:2, y = 2:3)
for i=1:2
  indicator = Expr(:quote, names(df)[i]))
  eval(DataFramesMeta.where_helper(:df, :($indicator .>= 2)))
end
```

Now the package intends you to do something like this:
```julia
where(df, DF -> DF[:x] .>=2)
```

**Comment by tshort** [comment]
This should be possible with an extension to DataFrames. I don't encourage
the eval approach. Behind the scenes, all of the macros are based on the
`@with` macro. The following

@with(df, :a  + :b)

is converted into:

dummyfun(a, b) = a + b
dummyfun(df[:a], df[:b])

I think that macro could be extended to allow something like:

@with(df, :a + !(indicator))

That needs to be converted into:

dummyfun(a, indicator) = a + indicator
dummyfun(df[:a], df[indicator])    # note there's no : on indicator

That should work. It'll have to be an exercise left to the reader,
unfortunately. Also, I just picked on `!`. It probably needs to be
something unique, maybe even a unicode operator.

**Comment by matthieugomez** [comment]
@tshort Thanks for commenting. I'm really impressed by the package. I think it's very good!

**Comment by matthieugomez** [comment]
One issue with my proposal (i.e. a `select` function that would mirror the `@select` macro  in the same way `select_` mirrors `select` in `dplyr`) is the discrepancy between selecting a column `:x` vs the transformation of a column `:(2 * :x)`. 
```julia
using DataFrames, DataFramesMeta
df = DataFrame(x = 1:2, y = 2:3)
indicator = :x
select(df, indicator)
select(df, :(2 * $(Expr(:quote, indicator)))
```
In some sense `:x` should be `:(:x)` in all these macros. 

One way to avoid this problem would be to refer to dataframe colums by `x` rather than `:x` in all these macros. This is also what dplyr does: variables are evaluated in the dataframe environment first and then in the caller environment. But then we enter the problems described in the README about anonymous functions inside `@with`. I'm sure there are more scope issues.
