### ISSUE TITLE
Ergonomic ways of recoding data

### ISSUE THREAD

**Issue by tshort** [JuliaStats/DataFramesMeta.jl#42]
This issue parallels https://github.com/JuliaStats/DataFrames.jl/issues/369. 

`@byrow!` may be close to what @nalimilan is after in the issue above. Here is a recoding example:

```julia
n = nrow(df)
df[:x] = Array(Int, n)
df[:y] = NullableArray(Float64, n)
@byrow! df begin
    :x = :a > 1 ? 4 : 9
    :y = :a * :b
end
```
The main irritation with the code above is allocating new columns. That could be handled by extending `@transform` or making a new macro that does something similar:

```julia
@transform(df, x = Array{Int}, y = NullableArray{Float64})
```
Another option is to add a feature to `@byrow!` that does this:

```julia
@byrow! df let x = Array{Int},
               y = NullableArray{Float64}
    :x = :a > 1 ? 4 : 9
    :y = :a * :b
end
```
Or:
```julia
@byrow! df begin
    @newcol x = Array{Int}
    @newcol y = NullableArray{Float64}
    :x = :a > 1 ? 4 : 9
    :y = :a * :b
end
```
Any opinions on these or other approaches? Any other features that `byrow!` needs to better recode data?

**Comment by nalimilan** [comment]
That's really cool. I would say the ideal solution would be to automatically create new columns, choosing the most appropriate type like Julia does for variables. Though I guess it would be tricky to decide whether to use a `NullableArray` or a standard array.

Given it may be hard to get this to work, an explicit syntax is a good solution (be it temporary or final). I think I'd prefer the `@newcol` form, but writing `@newcol x::Array{Int}` to match the standard Julia syntax. Actually, maybe `@byrow!` could detect type assertions and treat them as declarations of a new column, without even `@newcol`.

Then there's also the question of how to allow propagating null values. I guess we need to wait for the `@lift` macro to work fine in NullableArrays.jl before implementing this.

Finally, there's the minor annoyance of writing `:x` instead of `x`, which we discussed elsewhere already. But that would really be the icing on the cake: I think we can close this issue even if we don't have it. :-)

PS: Your example above doesn't work when copy/pasting: looks like you forgot one line creating `df`. See also https://github.com/JuliaStats/DataFrames.jl/issues/933
